echo Starting database container...
docker run -d -p 9042:9042 --rm --name cassandra -v cassandra-dev:/var/lib/cassandra cassandra:latest
echo Waiting for database to initialize...
sleep 45
echo Performing queued database updates...
bash update.sh
sleep 5
echo Starting WickedHost...
java -jar whost # no & detach here