echo Attempting to create scripts directory...
docker container exec -it cassandra mkdir scripts
echo Loading update scripts...
docker cp update.cql cassandra:/scripts/
echo Executing update scripts...
docker container exec -it cassandra cqlsh -f scripts/update.cql
echo Removing update scripts...
docker container exec -it cassandra rm scripts/update.cql
rm update.cql
echo Updates completed.